[env:seeed_xiao_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_24:58:7C:E2:8F:60-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_24:58:7C:E2:8F:60-if00
upload_speed = 921600
monitor_rts = 0
monitor_dtr = 0
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=1
    -I$PROJECT_CORE_DIR/packages/framework-arduinoespressif32/libraries/Network/src
    -I$PROJECT_CORE_DIR/packages/framework-arduinoespressif32/libraries/FS/src
board_build.partitions = huge_app.csv
lib_ldf_mode = deep+
lib_deps = 
    esp32-camera
    https://github.com/husarnet/husarnet-esp32.git
    bblanchon/ArduinoJson @ ^6.21.3